#
# .github/master.yml
#
# What happens when new stuff is merged into the 'master' branch.
#
name: Build and run tests
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Application test (on Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: true #npm test

  test-rules:
    name: Test security rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install dependencies (rules-test)
        run: cd rules-tests && npm install
      - name: Run rules tests
        run: cd rules-tests && npm test
