#
# builds/cloudbuild.yaml
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home

# - when push or PR targeting 'master'
#   - if changes in 'packages/backend' (other than '.md' or '.images'):
#     - cd packages/backend
#     - npm install
#     - npm test
#     - npm run deploy

# tbd. app, app-deploy-ops

# Non-DRY and verbose, since we cannot use '<<: &anchor' and '<<: *anchor' YAML syntax. 😢
#
steps:
- name: eu.gcr.io/groundlevel-160221/firebase-custom-builder
  entrypoint: bash
  args: ['-c', 'pwd']
  dir: packages/backend
#- name: eu.gcr.io/groundlevel-160221/firebase-custom-builder
#  entrypoint: bash
#  args: ['-c', 'env']
- name: eu.gcr.io/groundlevel-160221/firebase-custom-builder
  entrypoint: npm
  args: ['install']
  dir: packages/backend
- name: eu.gcr.io/groundlevel-160221/firebase-custom-builder
  entrypoint: npm
  args: ['test']
  dir: packages/backend
- name: eu.gcr.io/groundlevel-160221/firebase-custom-builder
  entrypoint: npm
  args: ['run', 'deploy']
  dir: packages/backend

#included files: packages/backend/* but not .md, .images
