#
# builds/cloudbuild.yaml
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# Triggers:
#   - changes in 'packages/backend'

# tbd. app, app-deploy-ops (maybe in separate YAML files??)

# - when push or merge targeting 'master'
#   - if changes in 'packages/backend' (other than '.md' or '.images'):
#     - cd packages/backend
#     - npm install
#     - npm test
#     - npm run deploy

# - when a PR targeting 'master' is being created
#   - if changes in 'packages/backend' (other than '.md' or '.images'):
#     - cd packages/backend
#     - npm install
#     - npm test

# Non-DRY and verbose, since we cannot use '<<: &anchor' and '<<: *anchor' YAML syntax. 😢
#
steps:
- name: eu.gcr.io/$PROJECT_ID/firebase-custom-builder
  entrypoint: bash
  args: ['-c', 'pwd']
  dir: packages/backend
#
- name: eu.gcr.io/$PROJECT_ID/firebase-custom-builder
  entrypoint: npm
  args: ['install']
  dir: packages/backend
#- name: eu.gcr.io/$PROJECT_ID/firebase-custom-builder
#  entrypoint: bash
#  args: ['-c', 'ls -al']
#  dir: packages/backend/functions
#
- name: eu.gcr.io/$PROJECT_ID/firebase-custom-builder
  entrypoint: npm
  args: ['test']
  dir: packages/backend
#
# --- Deploy
#
- name: eu.gcr.io/$PROJECT_ID/firebase-custom-builder
  entrypoint: firebase
  args: ['use', '--add', '$PROJECT_ID']
  dir: packages/backend
#
# Deploy fails. We can live with manual deployments, for a while...
- name: eu.gcr.io/$PROJECT_ID/firebase-custom-builder
  entrypoint: npm
  args: ['run', 'deploy']
  dir: packages/backend
