#
# builds/cloudbuild.pr.yaml
#
# Triggers:
#   - PR towards 'master' or 'staging' branch
#
# Runtime environment:
#   - Current directory is '/workspace/...', based on the 'dir' field
#
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#

substitutions:
  _BUILDER_TAG: 9.11.0-node16-npm7

# Non-DRY and verbose, since we cannot use '<<: &anchor' and '<<: *anchor' YAML syntax.. 💧😥
#
steps:
# DEBUG

# Root install
#
# Note: 'patch' is added and used within the same CI step, since changes outside of '/workspace' don't carry from step to step.
#
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: bash
  args: ['-c', 'apk --no-cache add patch && npm install']

# Backend
#
# Install 'app' dependencies only if backend passes.
#
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['install']
  dir: packages/backend
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['test']
  dir: packages/backend

# App
#
# tbd. Cypress is not available on images based on Alpine.
#     - track https://github.com/cypress-io/cypress/issues/419
#     - build our own, based on Cypress node image (add JVM, emulators, ...)
#
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['install']
  dir: packages/app

#- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
#  entrypoint: npm
#  args: ['test']
#  dir: packages/app

# --- Timeout
#
# Local:        ...
# Cloud Build:  2m58s (Cypress tests skipped)
#
timeout: 240s
